# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4333428f6761500c4a5231fdf0299cc5242187d0d4ea6c8442eab708bdfec18fd3399b7f3dc98feb229e84f8b0d24b0f3ae32de7e5a959e12e562575d9ed11b

test:
  secret_key_base: 18e4c65c352e90d9ffa8bdc828da68719af9afe00b14a148957066786bfe09a55c119dda8506281a9cc10e6533c65e82d60d8caa029df2dc137595c83a972255

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
